chore: update model training workflow with permissions and enhanced checks

diff --git a/.github/workflows/model-training.yml b/.github/workflows/model-training.yml
--- a/.github/workflows/model-training.yml
+++ b/.github/workflows/model-training.yml
@@ -9,8 +9,12 @@ on:
 #      - 'data/**'
 #      - 'sentiment_model_trainer/**'
 
+permissions:
+  contents: write
+
 jobs:
   build:
+    name: Train and Release Model
     runs-on: ubuntu-latest
 
     steps:
@@ -35,19 +39,27 @@ jobs:
           python -m pip install --upgrade pip
           pip install -r requirements.txt
 
+      - name: Sync DVC Data
+        run: |
+          dvc pull
+
       - name: Train Model with DVC
         run: |
           dvc repro
 
-      - name: Check model exists
-      - run: |
-          if [ ! -f models/sentiment-model.pkl ]; then echo "Model file does not exist. Exiting." exit 1; fi
+      - name: Check for model file
+        run: |
+          if [ ! -f "models/sentiment-model.pkl" ]; then
+            echo "Model file 'models/sentiment-model.pkl' not found after 'dvc repro'."
+            exit 1
+          fi
+          echo "Model file found."
 
       - name: Set Release Version
         id: set_version
         run: echo "RELEASE_VERSION=$(date +'%Y.%m.%d-%H%M%S')" >> $GITHUB_ENV
 
-      - name: Upload Model to GitHub Releases
+      - name: Create GitHub Release
         #if: github.ref == 'refs/heads/main'
         uses: softprops/action-gh-release@v2
         with:
@@ -55,5 +67,5 @@ jobs:
               models/sentiment-model.pkl
           tag_name: "v${{ env.RELEASE_VERSION }}"
           generate_release_notes: true
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        # env:
+        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
